defaultStake: 10000
defaultFee: 2000
borChainId: "15001"
heimdallChainId: heimdall-15001
contractsBranch: 8e95fa49300894caf7e59af837d62cff20768539
genesisContractsBranch: 802002775eca4c3493f3a613bb790f1311423cef
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 3
numOfNonValidators: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#c5569e4da9ebe0ce4e63aec571966c71234f7cfc"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
