defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch:
heimdallBranch:
contractsBranch: mardizzone/pos-880-revert
sprintSize: 64
blockNumber: '2'
blockTime: '0'
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#develop"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
