# Repositories
borRepo: https://github.com/maticnetwork/bor.git
borBranch: develop

# TODO-HV2: Remove this once heimdall-v2 is public.
# Use this format for heimdall-v2: https://<username>:<token>@github.com/0xPolygon/heimdall-v2.git
heimdallRepo: https://github.com/0xPolygon/heimdall-v2.git
heimdallBranch: develop

contractsRepo: https://github.com/0xPolygon/pos-contracts.git
contractsBranch: arya/matic-cli/pos-1869

genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master

# Defaults
devnetType: docker
defaultStake: 10000
defaultFee: 2000

# L1
ethURL: http://localhost:9545 # Use localhost for local deployments
ethHostUser: ubuntu

# Heimdall
heimdallChainId: heimdall-15005
# TODO-HV2: Remove this once heimdall-v2 is public.
# Use this format for heimdall-v2: https://<username>:<token>@github.com/0xPolygon/heimdall-v2.git#develop
heimdallDockerBuildContext: https://github.com/0xPolygon/heimdall-v2.git#develop

# Bor
borChainId: 15005
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop

sprintSize: '64'
sprintSizeBlockNumber: '0'
blockNumber: '0'
blockTime: '2'

numOfBorValidators: 1
numOfBorSentries: 1
numOfBorArchiveNodes: 0

devnetBorUsers: ubuntu,ubuntu
devnetBorHosts: localhost # Use localhost for local deployments
devnetBorFlags: config,config

# Erigon
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
