defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borRepo: https://github.com/maticnetwork/bor.git
borBranch: develop
heimdallRepo: https://github.com/maticnetwork/heimdall.git
heimdallBranch: develop
contractsRepo: https://github.com/maticnetwork/contracts.git
contractsBranch: 2ed59de3641c407c64def1b40bcd090cb9cc048a # todo change to master once contracts team merges the PR
genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
devnetBorUsers: ubuntu,ubuntu
devnetBorHosts:
  - 35.92.248.232
