defaultStake: 10000
defaultFee: 2000
borChainId: 4052
heimdallChainId: heimdall-4052
borBranch: c5569e4da9ebe0ce4e63aec571966c71234f7cfc # todo change to develop once https://polygon.atlassian.net/browse/POS-979 is solved
heimdallBranch: develop
contractsBranch: mardizzone/node-upgrade
genesisContractsBranch: master
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 2
numOfNonValidators: 1
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: https://github.com/maticnetwork/bor.git#c5569e4da9ebe0ce4e63aec571966c71234f7cfc # todo change to develop once https://polygon.atlassian.net/browse/POS-979 is solved
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
devnetBorUsers: ubuntu,ubuntu,ubuntu
devnetBorHosts:
  - 34.222.87.252
