defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch: v0.2.16
heimdallBranch: v0.2.10
contractsBranch: arpit/v0.3.1-backport
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://ganache:9545
devnetType: docker
ethHostUser: ubuntu
