defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch:
heimdallBranch:
contractsBranch: arpit/v0.3.2-backport
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://ganache:9545
ethHostUser: ubuntu
devnetType: docker
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#develop"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
