defaultStake: 10000
defaultFee: 2000
borChainId: "15001"
heimdallChainId: heimdall-15001
borBranch: develop
heimdallBranch: develop
contractsBranch: jc/v0.3.1-backport
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://ganache:9545
devnetType: docker
