# Repositories
borRepo: https://github.com/maticnetwork/bor.git
borBranch: raneet10/heimdallv2-changes

heimdallRepo: https://github.com/0xPolygon/heimdall-v2.git
heimdallBranch: develop

contractsRepo: https://github.com/0xPolygon/pos-contracts.git
contractsBranch: anvil-pos

genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master

# Defaults
devnetType: docker
defaultStake: 10000
defaultFee: 2000

# L1
ethURL: http://anvil:9545 # use localhost for local deployments
ethHostUser: ubuntu

# Misc
mnemonic: "clock radar mass judge dismiss just intact mind resemble fringe diary casino"

# Heimdall
heimdallChainId: heimdall-15005
heimdallDockerBuildContext: https://github.com/0xPolygon/heimdall-v2.git#develop

# Bor
borChainId: 15005
borDockerBuildContext: https://github.com/maticnetwork/bor.git#raneet10/heimdallv2-changes

blockTime: '2'
blockNumber: '0'

sprintSize: '64'
sprintSizeBlockNumber: '0'

# Bor
numOfBorValidators: 3
numOfBorSentries: 1
numOfBorArchiveNodes: 0

devnetBorUsers: ubuntu,ubuntu,ubuntu,ubuntu
devnetBorFlags: config,config,config,config

# Erigon
numOfErigonValidators: 0
numOfErigonSentries: 0
numOfErigonArchiveNodes: 0
