receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk: null
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load: null
      memory: null
      network: null
      processes: null
  prometheus:
    config:
      scrape_configs:
        - job_name: otelcol
          scrape_interval: 10s
          static_configs:
            - targets:
                - 0.0.0.0:8888
processors:
  batch:
    timeout: 10s
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
        - otlp
        - prometheus
      processors:
        - batch
      exporters:
        - datadog
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - datadog
