defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borRepo: https://github.com/maticnetwork/bor.git
borBranch: develop
heimdallRepo: https://github.com/maticnetwork/heimdall.git
heimdallBranch: develop
contractsRepo: https://github.com/maticnetwork/contracts.git
contractsBranch: mardizzone/node-16
genesisContractsRepo: https://github.com/maticnetwork/genesis-contracts.git
genesisContractsBranch: master
sprintSize: 64
sprintSizeBlockNumber: 0
blockNumber: '0'
blockTime: '2'
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
