defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch: develop
heimdallBranch: develop
contractsBranch: arpit/v0.3.1-backport
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
