defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: v0.2.16
heimdallBranch: v0.2.10
contractsBranch: arpit/v0.3.1-backport
sprintSize: 64
blockNumber: 0,64
blockTime: 2,5
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://34.221.108.173:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 34.221.108.173
  - 54.149.236.148
devnetHeimdallHosts:
  - 34.221.108.173
  - 54.149.236.148
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
