defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch:
heimdallBranch:
contractsBranch: arpit/v0.3.2-backport
sprintSize:
blockNumber:
blockTime:
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 54.202.55.147
  - 54.202.55.147
devnetHeimdallHosts:
  - 54.202.55.147
  - 54.202.55.147
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#develop"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
