defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: develop
heimdallBranch: develop
contractsBranch: jc/v0.3.1-backport
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://54.200.193.251:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 54.200.193.251
  - 54.184.234.43
devnetHeimdallHosts:
  - 54.200.193.251
  - 54.184.234.43
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
