defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: c5569e4da9ebe0ce4e63aec571966c71234f7cfc
heimdallBranch: develop
contractsBranch: mardizzone/node-upgrade
genesisContractsBranch: mardizzone/node-upgrade
sprintSize: 64
blockNumber: '0'
blockTime: '2'
numOfValidators: 2
numOfNonValidators: 1
ethURL: http://35.90.65.125:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 35.90.65.125
  - 35.86.86.76
  - 35.92.233.84
devnetHeimdallHosts:
  - 35.90.65.125
  - 35.86.86.76
  - 35.92.233.84
devnetBorUsers:
  - ubuntu
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
