defaultStake: 10000
defaultFee: 2000
borChainId:
heimdallChainId:
borBranch:
heimdallBranch:
contractsBranch: arpit/v0.3.2-backport
numOfValidators: 2
numOfNonValidators: 0
ethURL: http://172.20.1.100:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetHeimdallHosts:
  - 172.20.1.100
  - 172.20.1.101
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: "https://github.com/maticnetwork/bor.git#develop"
heimdallDockerBuildContext: "https://github.com/maticnetwork/heimdall.git#develop"
