defaultStake: 10000
defaultFee: 2000
borChainId: 15005
heimdallChainId: heimdall-4052
borBranch: v0.2.16
heimdallBranch: v0.2.10
contractsBranch: arpit/v0.3.1-backport
sprintSize: 64
blockNumber: 0,64
blockTime: 2,5
numOfValidators: 1
numOfNonValidators: 1
ethURL: http://35.88.64.66:9545
ethHostUser: ubuntu
devnetType: remote
devnetBorHosts:
  - 35.88.64.66
  - 34.220.161.74
devnetHeimdallHosts:
  - 35.88.64.66
  - 34.220.161.74
devnetBorUsers:
  - ubuntu
  - ubuntu
devnetHeimdallUsers:
  - ubuntu
  - ubuntu
borDockerBuildContext: https://github.com/maticnetwork/bor.git#develop
heimdallDockerBuildContext: https://github.com/maticnetwork/heimdall.git#develop
