name: CI-LINT
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18.19.0'

jobs:
  lint:
    name: Prettier and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: matic-cli
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm dependencies
        working-directory: matic-cli
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Run prettier
        working-directory: matic-cli
        run: npm run prettier:check

      - name: Run lint
        working-directory: matic-cli
        run: npm run lint:check
