name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Prettier and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: matic-cli
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'

      - name: Install npm dependencies
        run: |
          cd matic-cli
          npm install --prefer-offline --no-audit --progress=false

      - name: Run prettier
        run: |
          cd matic-cli
          npm run prettier:check

      - name: Run lint
        run: |
          cd matic-cli
          npm run lint:check

  integration-tests:
    permissions:
      id-token: write
      contents: write
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    strategy:
      matrix:
        os: [ubuntu-20.04] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: matic-cli

      - name: Create .env file
        continue-on-error: true
        run: |
          cd matic-cli
          cp .env.example .env
          sed -i 's,YOUR_IDENTIFIER,matic-cli-ci,' .env
          sed -i 's,aws-key,matic-cli-ci-key,' .env
          sed -i 's,/absolute/path/to/your/,/home/runner/work/matic-cli/matic-cli/matic-cli/aws/,' .env
          sed -i 's,MATIC_CLI_BRANCH=master,MATIC_CLI_BRANCH=${{ github.head_ref || github.ref_name }},' .env

      - name: Configure AWS credentials
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: GithubActionsSession

      - name: Create aws key pair
        continue-on-error: true
        run: |
          cd matic-cli
          mkdir aws
          cd aws
          aws ec2 create-key-pair --key-name matic-cli-ci-key --key-type rsa --key-format pem --output text > matic-cli-ci-key.pem
          chmod 600 matic-cli-ci-key.pem

      - name: Setup node
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'

      - name: Install npm dependencies
        continue-on-error: true
        run: |
          cd matic-cli
          npm install --prefer-offline --no-audit --progress=false

      - name: Init devnet
        continue-on-error: true
        run: |
          cd matic-cli
          ./bin/express-cli --init

      - name: Start devnet
        continue-on-error: true
        run: |
          cd matic-cli/deployments/devnet-1
          ../../bin/express-cli --start

      - name: Run smoke tests
        continue-on-error: true
        run: |
          cd matic-cli/deployments/devnet-1
          ../../bin/express-cli --send-state-sync
          cd -
          timeout 20m bash matic-cli/.github/smoke_test.sh

      - name: Destroy devnet
        continue-on-error: true
        if: always()
        run: |
          cd matic-cli/deployments/devnet-1
          echo "Running --destroy"
          ../../bin/express-cli --destroy

      - name: Delete aws key pair
        continue-on-error: true
        if: always()
        run: |
          cd matic-cli/aws
          aws ec2 delete-key-pair --key-name matic-cli-ci-key
