name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Prettier and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: matic-cli
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: Install npm dependencies
        working-directory: matic-cli
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Run prettier
        working-directory: matic-cli
        run: npm run prettier:check

      - name: Run lint
        working-directory: matic-cli
        run: npm run lint:check

  integration-tests:
    permissions:
      id-token: write
      contents: write
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    strategy:
      matrix:
        os: [ubuntu-20.04] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: matic-cli

      - name: Create .env file
        working-directory: matic-cli
        run: |
          cp .env.example .env
          sed -i 's,YOUR_IDENTIFIER,matic-cli-ci,' .env
          sed -i 's,aws-key,matic-cli-ci-key,' .env
          sed -i 's,/absolute/path/to/your/,/home/runner/work/matic-cli/matic-cli/matic-cli/aws/,' .env
          sed -i 's,MATIC_CLI_BRANCH=master,MATIC_CLI_BRANCH=${{ github.head_ref || github.ref_name }},' .env

      - name: Get GitHub action runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Create secret.tfvars
        working-directory: matic-cli
        run: |
          touch secret.tfvars
          echo "SG_CIDR_BLOCKS=[\"${{ steps.ip.outputs.ipv4 }}/32\"]" >> secret.tfvars

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/MaticCLIGitHubActionsRole
          role-session-name: GithubActionsSession

      - name: Create aws key pair
        working-directory: matic-cli
        run: |
          mkdir aws
          cd aws
          aws ec2 create-key-pair --key-name matic-cli-ci-key --key-type rsa --key-format pem --query "KeyMaterial" --output text > matic-cli-ci-key.pem
          chmod 700 matic-cli-ci-key.pem

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install npm dependencies
        working-directory: matic-cli
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Init devnet
        working-directory: matic-cli
        run: ./bin/express-cli.js --init aws

      - name: Start devnet
        working-directory: matic-cli/deployments/devnet-1
        run: |
          ls -la
          ../../bin/express-cli.js --start

      - name: Run stateSynced and checkpoint tests
        working-directory: matic-cli/deployments/devnet-1
        run: |
          ../../bin/express-cli.js --send-state-sync
          timeout 20m ../../bin/express-cli.js --monitor exit

      - name: Run smart contracts events tests
        working-directory: matic-cli/deployments/devnet-1
        run: |
          timeout 5m ../../bin/express-cli.js --send-staked-event 1
          timeout 5m ../../bin/express-cli.js --send-stakeupdate-event 1
          timeout 5m ../../bin/express-cli.js --send-topupfee-event 1
          timeout 10m ../../bin/express-cli.js --send-unstakeinit-event 1

      - name: Destroy devnet
        if: always()
        working-directory: matic-cli/deployments/devnet-1
        run: |
          echo "Running --destroy"
          ../../bin/express-cli.js --destroy

      - name: Delete aws key pair
        if: always()
        working-directory: matic-cli/aws
        run: aws ec2 delete-key-pair --key-name matic-cli-ci-key
